[2022-12-27T03:17:52.222+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T03:17:40.630548+00:00 [queued]>
[2022-12-27T03:17:52.271+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T03:17:40.630548+00:00 [queued]>
[2022-12-27T03:17:52.273+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T03:17:52.275+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-27T03:17:52.277+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T03:17:54.067+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-27 03:17:40.630548+00:00
[2022-12-27T03:17:54.099+0000] {standard_task_runner.py:55} INFO - Started process 174 to run task
[2022-12-27T03:17:54.111+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-27T03:17:40.630548+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpc6kyay_0']
[2022-12-27T03:17:54.118+0000] {standard_task_runner.py:83} INFO - Job 294: Subtask extract_test
[2022-12-27T03:17:54.659+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-27T03:17:40.630548+00:00 [running]> on host b40088984618
[2022-12-27T03:17:54.985+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T03:17:40.630548+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T03:17:40.630548+00:00
[2022-12-27T03:17:54.994+0000] {conn.py:372} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: connecting to broker:9092 [('172.25.0.4', 9092) IPv4]
[2022-12-27T03:17:54.996+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T03:17:54.999+0000] {conn.py:401} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: Connection complete.
[2022-12-27T03:17:55.110+0000] {conn.py:1106} INFO - Broker version identifed as 1.0.0
[2022-12-27T03:17:55.111+0000] {conn.py:1108} INFO - Set configuration api_version=(1, 0, 0) to skip auto check_version requests on startup
[2022-12-27T03:17:55.119+0000] {subscription_state.py:171} INFO - Updating subscribed topics to: ('projek_akhir',)
[2022-12-27T03:17:55.925+0000] {streaming.py:217} ERROR - Stream encountered HTTP error: 429
[2022-12-27T03:17:55.930+0000] {streaming.py:111} ERROR - HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
[2022-12-27T03:18:35.891+0000] {local_task_job.py:224} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2022-12-27T03:18:35.913+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 174. PIDs of all processes in the group: [174]
[2022-12-27T03:18:35.915+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 174
[2022-12-27T03:18:35.920+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-27T03:18:35.932+0000] {streaming.py:203} ERROR - Stream encountered an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/tweepy/streaming.py", line 120, in _connect
    sleep(http_error_wait)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-12-27T03:18:35.981+0000] {logging_mixin.py:137} INFO - Disconnected
[2022-12-27T03:18:36.001+0000] {streaming.py:193} INFO - Stream disconnected
[2022-12-27T03:18:36.022+0000] {conn.py:372} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: connecting to broker:9092 [('172.25.0.4', 9092) IPv4]
[2022-12-27T03:18:36.134+0000] {conn.py:401} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: Connection complete.
[2022-12-27T03:18:36.251+0000] {cluster.py:376} INFO - Group coordinator for consumers is (1003, 'broker', 9092, None)
[2022-12-27T03:18:36.255+0000] {base.py:688} INFO - Discovered coordinator 1003 for group consumers
[2022-12-27T03:18:36.259+0000] {base.py:735} INFO - Starting new heartbeat thread
[2022-12-27T03:18:36.263+0000] {consumer.py:342} INFO - Revoking previously assigned partitions () for group consumers
[2022-12-27T03:18:36.267+0000] {conn.py:372} INFO - <BrokerConnection node_id=1003 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: connecting to broker:9092 [('172.25.0.4', 9092) IPv4]
[2022-12-27T03:18:36.375+0000] {conn.py:401} INFO - <BrokerConnection node_id=1003 host=broker:9092 <connecting> [IPv4 ('172.25.0.4', 9092)]>: Connection complete.
[2022-12-27T03:18:36.378+0000] {conn.py:811} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connected> [IPv4 ('172.25.0.4', 9092)]>: Closing connection. 
[2022-12-27T03:18:36.482+0000] {base.py:447} INFO - (Re-)joining group consumers
[2022-12-27T03:18:36.498+0000] {base.py:516} INFO - Elected group leader -- performing partition assignments using range
[2022-12-27T03:18:36.512+0000] {base.py:333} INFO - Successfully joined group consumers with generation 3
[2022-12-27T03:18:36.515+0000] {subscription_state.py:257} INFO - Updated partition assignment: [('projek_akhir', 0)]
[2022-12-27T03:18:36.517+0000] {consumer.py:239} INFO - Setting newly assigned partitions (('projek_akhir', 0),) for group consumers
[2022-12-27T03:18:36.923+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 99, in start_etl
    load(msg.value)
  File "/opt/airflow/dags/etl.py", line 88, in load
    temp = json.loads(msg)
  File "/usr/local/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not ConsumerRecord
[2022-12-27T03:18:37.091+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=extract_test, execution_date=20221227T031740, start_date=20221227T031752, end_date=20221227T031837
[2022-12-27T03:18:37.399+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 294 for task extract_test (the JSON object must be str, bytes or bytearray, not ConsumerRecord; 174)
[2022-12-27T03:18:37.670+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=174, status='terminated', exitcode=1, started='03:17:54') (174) terminated with exit code 1
