[2022-12-26T23:58:44.909+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-26T21:35:14.053527+00:00 [queued]>
[2022-12-26T23:58:45.097+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-26T21:35:14.053527+00:00 [queued]>
[2022-12-26T23:58:45.104+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T23:58:45.106+0000] {taskinstance.py:1284} INFO - Starting attempt 5 of 6
[2022-12-26T23:58:45.108+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T23:58:45.250+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-26 21:35:14.053527+00:00
[2022-12-26T23:58:45.295+0000] {standard_task_runner.py:55} INFO - Started process 2143 to run task
[2022-12-26T23:58:45.335+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-26T21:35:14.053527+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmponyf8h0q']
[2022-12-26T23:58:45.354+0000] {standard_task_runner.py:83} INFO - Job 146: Subtask extract_test
[2022-12-26T23:58:50.555+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-26T21:35:14.053527+00:00 [running]> on host 3dc0e72111ec
[2022-12-26T23:58:51.093+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T21:35:14.053527+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-26T21:35:14.053527+00:00
[2022-12-26T23:58:51.108+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T23:58:51.110+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T23:58:51.112+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-26T23:58:51.120+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T23:58:51.124+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T23:58:51.128+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 14, in start_etl
    producer = KafkaProducer(bootstrap_servers=['broker'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 865, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-12-26T23:58:51.205+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=extract_test, execution_date=20221226T213514, start_date=20221226T235844, end_date=20221226T235851
[2022-12-26T23:58:51.248+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 146 for task extract_test (NoBrokersAvailable; 2143)
[2022-12-26T23:58:51.483+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-26T23:58:52.600+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
