[2022-12-27T00:49:11.737+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2022-12-27T00:49:11.746+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2022-12-27T00:49:11.747+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T00:49:11.747+0000] {taskinstance.py:1284} INFO - Starting attempt 6 of 6
[2022-12-27T00:49:11.748+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T00:49:11.758+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-26 00:00:00+00:00
[2022-12-27T00:49:11.766+0000] {standard_task_runner.py:55} INFO - Started process 3436 to run task
[2022-12-27T00:49:11.773+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpa1lllguy']
[2022-12-27T00:49:11.777+0000] {standard_task_runner.py:83} INFO - Job 154: Subtask extract_test
[2022-12-27T00:49:12.161+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test scheduled__2022-12-26T00:00:00+00:00 [running]> on host 3dc0e72111ec
[2022-12-27T00:49:12.310+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-26T00:00:00+00:00
[2022-12-27T00:49:12.324+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T00:49:12.326+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T00:49:12.329+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T00:49:12.333+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T00:49:12.335+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T00:49:12.337+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 14, in start_etl
    producer = KafkaProducer(bootstrap_servers=['broker'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 865, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-12-27T00:49:12.365+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=final_project_dag, task_id=extract_test, execution_date=20221226T000000, start_date=20221227T004911, end_date=20221227T004912
[2022-12-27T00:49:12.388+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 154 for task extract_test (NoBrokersAvailable; 3436)
[2022-12-27T00:49:12.443+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-27T00:49:12.525+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
