[2022-12-27T04:49:37.890+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:36:24.413497+00:00 [queued]>
[2022-12-27T04:49:37.996+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:36:24.413497+00:00 [queued]>
[2022-12-27T04:49:37.998+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:49:38.004+0000] {taskinstance.py:1284} INFO - Starting attempt 2 of 6
[2022-12-27T04:49:38.006+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:49:38.124+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-27 04:36:24.413497+00:00
[2022-12-27T04:49:38.190+0000] {standard_task_runner.py:55} INFO - Started process 94 to run task
[2022-12-27T04:49:38.213+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-27T04:36:24.413497+00:00', '--job-id', '375', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmp29zn_e32']
[2022-12-27T04:49:38.258+0000] {standard_task_runner.py:83} INFO - Job 375: Subtask extract_test
[2022-12-27T04:49:38.868+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:36:24.413497+00:00 [running]> on host 6026fe33842a
[2022-12-27T04:49:39.502+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T04:36:24.413497+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T04:36:24.413497+00:00
[2022-12-27T04:49:39.553+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:49:39.555+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:49:39.557+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:49:39.564+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:49:39.567+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:49:39.568+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 15, in start_etl
    producer = KafkaProducer(bootstrap_servers=['broker'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 865, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-12-27T04:49:39.630+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=extract_test, execution_date=20221227T043624, start_date=20221227T044937, end_date=20221227T044939
[2022-12-27T04:49:39.722+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 375 for task extract_test (NoBrokersAvailable; 94)
[2022-12-27T04:49:39.827+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-27T04:49:40.035+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
