[2022-12-27T04:55:11.648+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:40:30.365993+00:00 [queued]>
[2022-12-27T04:55:11.720+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:40:30.365993+00:00 [queued]>
[2022-12-27T04:55:11.726+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:55:11.729+0000] {taskinstance.py:1284} INFO - Starting attempt 3 of 6
[2022-12-27T04:55:11.732+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:55:11.945+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-27 04:40:30.365993+00:00
[2022-12-27T04:55:11.972+0000] {standard_task_runner.py:55} INFO - Started process 245 to run task
[2022-12-27T04:55:11.996+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-27T04:40:30.365993+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpirq21cz2']
[2022-12-27T04:55:12.010+0000] {standard_task_runner.py:83} INFO - Job 378: Subtask extract_test
[2022-12-27T04:55:12.375+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:40:30.365993+00:00 [running]> on host 6026fe33842a
[2022-12-27T04:55:12.959+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T04:40:30.365993+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T04:40:30.365993+00:00
[2022-12-27T04:55:12.993+0000] {conn.py:372} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: connecting to broker:9092 [('172.25.0.8', 9092) IPv4]
[2022-12-27T04:55:13.002+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:55:13.006+0000] {conn.py:410} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]> returned error 111. Disconnecting.
[2022-12-27T04:55:13.010+0000] {conn.py:811} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2022-12-27T04:55:13.032+0000] {conn.py:372} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: connecting to broker:9092 [('172.25.0.8', 9092) IPv4]
[2022-12-27T04:55:13.042+0000] {conn.py:410} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]> returned error 111. Disconnecting.
[2022-12-27T04:55:13.045+0000] {conn.py:811} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.25.0.8', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2022-12-27T04:55:13.051+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 15, in start_etl
    producer = KafkaProducer(bootstrap_servers=['broker'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 865, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-12-27T04:55:13.177+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=extract_test, execution_date=20221227T044030, start_date=20221227T045511, end_date=20221227T045513
[2022-12-27T04:55:13.303+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 378 for task extract_test (NoBrokersAvailable; 245)
[2022-12-27T04:55:13.397+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-27T04:55:13.695+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
