[2022-12-27T04:42:51.560+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:40:30.365993+00:00 [queued]>
[2022-12-27T04:42:53.460+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:40:30.365993+00:00 [queued]>
[2022-12-27T04:42:53.776+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:42:53.799+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 6
[2022-12-27T04:42:53.814+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-27T04:42:55.050+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-27 04:40:30.365993+00:00
[2022-12-27T04:43:00.066+0000] {standard_task_runner.py:55} INFO - Started process 1043 to run task
[2022-12-27T04:43:02.580+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-27T04:40:30.365993+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpfo2fkcmv']
[2022-12-27T04:43:04.783+0000] {standard_task_runner.py:83} INFO - Job 372: Subtask extract_test
[2022-12-27T04:43:40.089+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-27T04:40:30.365993+00:00 [running]> on host 6026fe33842a
[2022-12-27T04:44:54.080+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-27T04:40:30.365993+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-27T04:40:30.365993+00:00
[2022-12-27T04:44:57.487+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:44:57.833+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:44:58.241+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-27T04:44:58.781+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-27T04:44:58.797+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-27T04:44:58.827+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 15, in start_etl
    producer = KafkaProducer(bootstrap_servers=['broker'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 892, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-12-27T04:45:01.434+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=final_project_dag, task_id=extract_test, execution_date=20221227T044030, start_date=20221227T044251, end_date=20221227T044501
[2022-12-27T04:45:06.585+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 372 for task extract_test (NoBrokersAvailable; 1043)
[2022-12-27T04:45:41.335+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-27T04:45:55.138+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
