[2022-12-26T23:58:40.844+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-26T21:31:35.830697+00:00 [queued]>
[2022-12-26T23:58:40.907+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: final_project_dag.extract_test manual__2022-12-26T21:31:35.830697+00:00 [queued]>
[2022-12-26T23:58:40.909+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T23:58:40.910+0000] {taskinstance.py:1284} INFO - Starting attempt 6 of 6
[2022-12-26T23:58:40.911+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-26T23:58:41.057+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_test> on 2022-12-26 21:31:35.830697+00:00
[2022-12-26T23:58:41.109+0000] {standard_task_runner.py:55} INFO - Started process 2138 to run task
[2022-12-26T23:58:41.135+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'final_project_dag', 'extract_test', 'manual__2022-12-26T21:31:35.830697+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/final_project_dag.py', '--cfg-path', '/tmp/tmpwqllm_3b']
[2022-12-26T23:58:41.176+0000] {standard_task_runner.py:83} INFO - Job 144: Subtask extract_test
[2022-12-26T23:58:46.322+0000] {task_command.py:389} INFO - Running <TaskInstance: final_project_dag.extract_test manual__2022-12-26T21:31:35.830697+00:00 [running]> on host 3dc0e72111ec
[2022-12-26T23:58:46.823+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=kelompok 3
AIRFLOW_CTX_DAG_ID=final_project_dag
AIRFLOW_CTX_TASK_ID=extract_test
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T21:31:35.830697+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-26T21:31:35.830697+00:00
[2022-12-26T23:58:46.848+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T23:58:46.850+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T23:58:46.862+0000] {conn.py:1049} INFO - Probing node bootstrap-0 broker version
[2022-12-26T23:58:46.884+0000] {conn.py:1371} WARNING - DNS lookup failed for broker:9092, exception was [Errno -5] No address associated with hostname. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2022-12-26T23:58:46.885+0000] {conn.py:307} ERROR - DNS lookup failed for broker:9092 (AddressFamily.AF_UNSPEC)
[2022-12-26T23:58:46.890+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl.py", line 14, in start_etl
    producer = KafkaProducer(bootstrap_servers=['broker'])
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 381, in __init__
    **self.config)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 239, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/kafka/client_async.py", line 865, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-12-26T23:58:46.971+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=final_project_dag, task_id=extract_test, execution_date=20221226T213135, start_date=20221226T235840, end_date=20221226T235846
[2022-12-26T23:58:47.076+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 144 for task extract_test (NoBrokersAvailable; 2138)
[2022-12-26T23:58:47.327+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-26T23:58:50.468+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
